<script src="{{ asset('admin/js/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('admin/asset/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('admin/js/fastclick/lib/fastclick.js') }}"></script>
<script src="{{ asset('admin/asset/nprogress/nprogress.js') }}"></script>
<script src="{{ asset('admin/asset/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
<script src="{{ asset('admin/asset/iCheck/icheck.min.js') }}"></script>
<script src="{{asset('admin/js/ckeditor/ckeditor.js')}}"></script>
<script src="{{ asset('admin/js/custom.min.js') }}"></script>
<script src="{{ asset('admin/js/my-js.js') }}"></script>
<script src="{{ asset('admin/js/ajax.js') }}"></script>
<script src="{{ asset('admin/js/notify.js') }}"></script>
<script src="{{ asset('admin/js/notify.min.js') }}"></script>